fm_elfinder:
    instances:
        default:
            locale: 'ru'
            editor: ckeditor
            relative_path: false
            connector:
                roots:
                    uploads:
                        driver: LocalFileSystem
                        path: storage/images/content
                        upload_allow: ['image/png', 'image/jpg', 'image/jpeg']
                        upload_deny: ['all']
                        upload_max_size: 2M
