# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html
fos_ck_editor:
    default_config: content_config
    configs:
        description_config:
            toolbar: [
                [ 'Undo', 'Redo' ],
                [ 'Bold', 'Italic', 'Strike', '-', 'RemoveFormat' ],
                [ 'Scayt' ]
            ]
        content_config:
            toolbar: [
                [ 'Undo', 'Redo' ],
                [ 'Styles', 'Format' ],
                [ 'Bold', 'Italic', 'Strike', '-', 'RemoveFormat' ],
                [ 'NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote' ],
                [ 'Link', 'Unlink' ],
                [ 'Image', 'Table' ],
                [ 'Maximize' ],
                [ 'Scayt' ]
            ]
twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
